import AppKit
import CryptoKit
import XCTest
@testable import SnipSnipSnip

@MainActor
final class ClipboardHistoryStoreTests: XCTestCase {
    private var enabledPreferences: ClipboardPreferences {
        var preferences = ClipboardPreferences.default
        preferences.isEnabled = true
        return preferences
    }

    private func makeStore(named name: String) -> ClipboardHistoryStore {
        ClipboardHistoryStore(
            baseURL: FileManager.default.temporaryDirectory.appendingPathComponent(name, isDirectory: true),
            keyProvider: TestClipboardEncryptionKeyProvider()
        )
    }

    private func removeStore(named name: String) {
        try? FileManager.default.removeItem(at: FileManager.default.temporaryDirectory.appendingPathComponent(name, isDirectory: true))
    }

    func testDeduplicatesItemsByContentHashAndKeepsNewestTimelinePosition() {
        let storeName = "ClipboardHistoryStoreTests.deduplicates"
        removeStore(named: storeName)
        defer { removeStore(named: storeName) }

        let store = makeStore(named: storeName)
        let preferences = ClipboardPreferences.default

        store.recordText(
            "repeat value",
            sourceApp: ClipboardSourceApp(name: "Notes", bundleIdentifier: "com.apple.Notes"),
            preferences: preferences,
            copiedAt: Date(timeIntervalSince1970: 1)
        )
        store.recordText(
            "other value",
            sourceApp: ClipboardSourceApp(name: "Safari", bundleIdentifier: "com.apple.Safari"),
            preferences: preferences,
            copiedAt: Date(timeIntervalSince1970: 2)
        )
        store.recordText(
            "repeat value",
            sourceApp: ClipboardSourceApp(name: "Mail", bundleIdentifier: "com.apple.mail"),
            preferences: preferences,
            copiedAt: Date(timeIntervalSince1970: 3)
        )

        XCTAssertEqual(store.items.count, 2)
        XCTAssertEqual(store.items.first?.previewText, "repeat value")
        XCTAssertEqual(store.items.first?.sourceApp?.name, "Mail")
    }

    func testPrunesUnpinnedItemsByMaximumItemCount() {
        let storeName = "ClipboardHistoryStoreTests.prunesCount"
        removeStore(named: storeName)
        defer { removeStore(named: storeName) }

        let store = makeStore(named: storeName)
        let preferences = ClipboardPreferences(
            isEnabled: true,
            maxItemCount: 10,
            maxStorageMB: 25,
            ignoredApps: []
        )

        for index in 0..<14 {
            store.recordText("value \(index)", sourceApp: nil, preferences: preferences, copiedAt: Date(timeIntervalSince1970: TimeInterval(index)))
        }

        XCTAssertEqual(store.items.count, 10)
        XCTAssertEqual(store.items.first?.previewText, "value 13")
        XCTAssertEqual(store.items.last?.previewText, "value 4")
    }

    func testPrunesUnpinnedItemsByMaximumByteSize() {
        let storeName = "ClipboardHistoryStoreTests.prunesSize"
        removeStore(named: storeName)
        defer { removeStore(named: storeName) }

        let store = makeStore(named: storeName)
        let preferences = ClipboardPreferences(
            isEnabled: true,
            maxItemCount: 100,
            maxStorageMB: 25,
            ignoredApps: []
        )

        let imageData = Data(repeating: 7, count: 14 * 1_024 * 1_024)
        store.recordImageData(imageData, sourceApp: nil, preferences: preferences, copiedAt: Date(timeIntervalSince1970: 1))
        store.recordImageData(Data(repeating: 9, count: 14 * 1_024 * 1_024), sourceApp: nil, preferences: preferences, copiedAt: Date(timeIntervalSince1970: 2))

        var constrainedPreferences = preferences
        constrainedPreferences.maxStorageMB = 25
        store.prune(using: constrainedPreferences)

        XCTAssertEqual(store.items.count, 1)
        XCTAssertLessThanOrEqual(store.items.reduce(Int64(0)) { $0 + $1.byteSize }, constrainedPreferences.maxStorageBytes)
    }

    func testIgnoredAppsAndSensitiveTypesAreFiltered() {
        let preferences = ClipboardPreferences.default
        let sourceApp = ClipboardSourceApp(name: "Bitwarden", bundleIdentifier: "com.bitwarden.desktop")

        XCTAssertTrue(preferences.ignores(sourceApp))
        XCTAssertTrue(ClipboardPasteboardReader.containsSensitiveOrTransientType(["public.utf8-plain-text", "org.nspasteboard.ConcealedType"]))
        XCTAssertTrue(ClipboardPasteboardReader.containsSensitiveOrTransientType(["org.nspasteboard.TransientType"]))
        XCTAssertFalse(ClipboardPasteboardReader.containsSensitiveOrTransientType(["public.utf8-plain-text"]))
        XCTAssertFalse(ClipboardPasteboardReader.containsSensitiveOrTransientType(["public.utf8-plain-text", ClipboardPasteboardReader.autoGeneratedTypeName]))
    }

    func testAutoGeneratedPasteboardMarkerDoesNotSuppressReadableText() throws {
        let pasteboard = TestPasteboardService()
        pasteboard.setString("normal copied text", forType: .string)
        pasteboard.addType(ClipboardPasteboardReader.autoGeneratedTypeName)

        let snapshot = try XCTUnwrap(ClipboardPasteboardReader.readPasteboard(
            pasteboard,
            sourceApp: nil,
            preferences: .default
        ))

        XCTAssertEqual(snapshot, .text("normal copied text"))
    }

    func testClipboardMonitorRecordsCopiesAfterMonitoringStarts() async {
        let storeName = "ClipboardHistoryStoreTests.monitorRecords"
        removeStore(named: storeName)
        defer { removeStore(named: storeName) }

        let pasteboard = TestPasteboardService()
        let store = makeStore(named: storeName)
        let monitor = ClipboardMonitor(
            store: store,
            pasteboard: pasteboard,
            workspace: TestWorkspaceService()
        )

        monitor.start(preferences: enabledPreferences)
        pasteboard.setString("copy after start", forType: .string)

        await waitUntil {
            store.items.first?.previewText == "copy after start"
        }

        monitor.stop()
        XCTAssertEqual(store.items.first?.previewText, "copy after start")
    }

    func testClipboardMonitorRecordsPendingPasteboardChangeWhenMonitoringStarts() async {
        let storeName = "ClipboardHistoryStoreTests.monitorPendingStart"
        removeStore(named: storeName)
        defer { removeStore(named: storeName) }

        let pasteboard = TestPasteboardService()
        let store = makeStore(named: storeName)
        let monitor = ClipboardMonitor(
            store: store,
            pasteboard: pasteboard,
            workspace: TestWorkspaceService()
        )

        pasteboard.setString("copy before start", forType: .string)
        monitor.start(preferences: enabledPreferences)

        await waitUntil {
            store.items.first?.previewText == "copy before start"
        }

        monitor.stop()
        XCTAssertEqual(store.items.first?.previewText, "copy before start")
    }

    func testClipboardMonitorKeepsOnlyLatestPendingChangeWhileProcessing() async {
        let storeName = "ClipboardHistoryStoreTests.monitorLatestPending"
        removeStore(named: storeName)
        defer { removeStore(named: storeName) }

        let pasteboard = TestPasteboardService()
        let store = makeStore(named: storeName)
        let resolver = ControlledClipboardSnapshotResolver()
        let monitor = ClipboardMonitor(
            store: store,
            pasteboard: pasteboard,
            workspace: TestWorkspaceService(),
            snapshotResolver: { content in
                await resolver.resolve(content)
            }
        )

        monitor.start(preferences: enabledPreferences)
        pasteboard.setString("first", forType: .string)
        await waitUntil {
            await resolver.captureCount == 1
        }

        pasteboard.setString("superseded", forType: .string)
        try? await Task.sleep(nanoseconds: 300_000_000)
        pasteboard.setString("latest", forType: .string)
        try? await Task.sleep(nanoseconds: 300_000_000)

        await resolver.releaseNext()
        await waitUntil {
            await resolver.captureCount == 2
        }

        let capturedTexts = await resolver.capturedTexts
        XCTAssertEqual(capturedTexts, ["first", "latest"])

        await resolver.releaseNext()
        await waitUntil {
            store.items.count == 2
        }
        monitor.stop()

        XCTAssertEqual(Set(store.items.map(\.previewText)), ["first", "latest"])
        XCTAssertFalse(store.items.contains { $0.previewText == "superseded" })
    }

    func testClipboardMonitorDiscardsCopiesWhilePausedAndResumesCleanly() async {
        let storeName = "ClipboardHistoryStoreTests.monitorPause"
        removeStore(named: storeName)
        defer { removeStore(named: storeName) }
        let pasteboard = TestPasteboardService()
        let store = makeStore(named: storeName)
        let monitor = ClipboardMonitor(store: store, pasteboard: pasteboard, workspace: TestWorkspaceService())
        monitor.start(preferences: enabledPreferences)
        monitor.pause(until: .distantFuture)
        pasteboard.setString("private while paused", forType: .string)
        try? await Task.sleep(nanoseconds: 350_000_000)
        XCTAssertTrue(store.items.isEmpty)

        monitor.pause(until: nil)
        pasteboard.setString("record after resume", forType: .string)
        await waitUntil { store.items.first?.previewText == "record after resume" }
        monitor.stop()
        XCTAssertEqual(store.items.count, 1)
    }

    func testDefaultIgnoredAppsIncludeAdditionalPasswordManagers() {
        let preferences = ClipboardPreferences.default
        let managers = [
            ClipboardSourceApp(name: "mSecure", bundleIdentifier: "com.mseven.mSecure"),
            ClipboardSourceApp(name: "Keeper Password Manager", bundleIdentifier: "com.keepersecurity.passwordmanager"),
            ClipboardSourceApp(name: "RoboForm", bundleIdentifier: "com.siber.roboform"),
            ClipboardSourceApp(name: "Enpass", bundleIdentifier: "in.sinew.Enpass-Desktop"),
            ClipboardSourceApp(name: "KeeWeb", bundleIdentifier: "com.antelle.keeweb"),
            ClipboardSourceApp(name: "MacPass", bundleIdentifier: "com.hicknhacksoftware.MacPass"),
            ClipboardSourceApp(name: "Strongbox", bundleIdentifier: "com.strongboxsafe.Strongbox"),
            ClipboardSourceApp(name: "Secrets", bundleIdentifier: "com.outercorner.Secrets"),
            ClipboardSourceApp(name: "Buttercup", bundleIdentifier: "com.buttercup.desktop"),
            ClipboardSourceApp(name: "SafeInCloud", bundleIdentifier: "com.safe-in-cloud.SafeInCloud")
        ]

        for manager in managers {
            XCTAssertTrue(preferences.ignores(manager), "Expected default clipboard privacy filters to ignore \(manager.displayName).")
        }
    }

    func testRemoteClipboardMarkerWinsOverFrontmostFallbackSource() throws {
        let fallback = ClipboardSourceApp(name: "Microsoft Teams", bundleIdentifier: "com.microsoft.teams2")
        let sourceApp = ClipboardPasteboardReader.sourceApp(
            forPasteboardTypeNames: ["public.utf8-plain-text", ClipboardPasteboardReader.remoteClipboardTypeName],
            explicitSourceIdentifier: nil,
            fallbackSourceApp: fallback,
            workspace: TestWorkspaceService()
        )

        XCTAssertEqual(sourceApp?.name, "Universal Clipboard")
        XCTAssertEqual(sourceApp?.bundleIdentifier, ClipboardPasteboardReader.remoteClipboardTypeName)
    }

    func testExplicitPasteboardSourceWinsOverRemoteAndFrontmostSources() throws {
        let fallback = ClipboardSourceApp(name: "Microsoft Teams", bundleIdentifier: "com.microsoft.teams2")
        let sourceApp = ClipboardPasteboardReader.sourceApp(
            forPasteboardTypeNames: [
                "public.utf8-plain-text",
                ClipboardPasteboardReader.remoteClipboardTypeName,
                ClipboardPasteboardReader.sourceTypeName
            ],
            explicitSourceIdentifier: "com.apple.Safari",
            fallbackSourceApp: fallback,
            workspace: TestWorkspaceService()
        )

        XCTAssertEqual(sourceApp?.bundleIdentifier, "com.apple.Safari")
        XCTAssertNotEqual(sourceApp?.name, "Microsoft Teams")
    }

    func testSearchMatchesTextSourceAndType() {
        let storeName = "ClipboardHistoryStoreTests.search"
        removeStore(named: storeName)
        defer { removeStore(named: storeName) }

        let store = makeStore(named: storeName)
        store.recordText(
            "https://example.com/snip",
            sourceApp: ClipboardSourceApp(name: "Safari", bundleIdentifier: "com.apple.Safari"),
            preferences: .default
        )

        let item = try! XCTUnwrap(store.items.first)
        XCTAssertTrue(item.matchesSearchQuery("example"))
        XCTAssertTrue(item.matchesSearchQuery("Safari"))
        XCTAssertTrue(item.matchesSearchQuery("Link"))
        XCTAssertFalse(item.matchesSearchQuery("missing"))
    }

    func testPlainTextSanitizationAppliesOnlyToTextLikeItems() {
        let textItem = ClipboardItem(
            id: UUID(),
            kind: .text("Styled text"),
            previewText: "Styled text",
            searchableText: "Styled text",
            sourceApp: nil,
            copiedAt: Date(),
            isPinned: false,
            contentHash: "text",
            byteSize: 11
        )
        let linkItem = ClipboardItem(
            id: UUID(),
            kind: .link("https://example.com"),
            previewText: "Example",
            searchableText: "https://example.com Example",
            sourceApp: nil,
            copiedAt: Date(),
            isPinned: false,
            contentHash: "link",
            byteSize: 19
        )
        let imageItem = ClipboardItem(
            id: UUID(),
            kind: .image(assetName: "image.png"),
            previewText: "Image",
            searchableText: "Image",
            sourceApp: nil,
            copiedAt: Date(),
            isPinned: false,
            contentHash: "image",
            byteSize: 1024
        )

        XCTAssertEqual(textItem.plainTextValue, "Styled text")
        XCTAssertEqual(linkItem.plainTextValue, "https://example.com")
        XCTAssertTrue(textItem.supportsPlainTextSanitization)
        XCTAssertTrue(linkItem.supportsPlainTextSanitization)
        XCTAssertNil(imageItem.plainTextValue)
        XCTAssertFalse(imageItem.supportsPlainTextSanitization)
    }

    func testImageFileURLsAreReadAsImageSnapshotsWithFilenameMetadata() throws {
        let directory = FileManager.default.temporaryDirectory.appendingPathComponent("ClipboardHistoryStoreTests.imageFileURL", isDirectory: true)
        try? FileManager.default.removeItem(at: directory)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: directory) }

        let imageURL = directory.appendingPathComponent("image000000.jpg")
        let imageData = try XCTUnwrap(Self.jpegData())
        try imageData.write(to: imageURL)

        let snapshot = try XCTUnwrap(ClipboardPasteboardReader.imageFileSnapshot(for: [imageURL]))
        guard case let .imageData(data, title, searchableText) = snapshot else {
            return XCTFail("Expected image data for copied image file URLs.")
        }

        XCTAssertFalse(data.isEmpty)
        XCTAssertEqual(title, "image000000.jpg")
        XCTAssertTrue(searchableText?.contains("image000000.jpg") == true)
    }

    func testWebURLsReadFromPasteboardURLObjectsAreLinksNotFiles() throws {
        let storeName = "ClipboardHistoryStoreTests.webURL"
        removeStore(named: storeName)
        defer { removeStore(named: storeName) }

        let webURL = try XCTUnwrap(URL(string: "https://www.youtube.com/watch?v=abc123"))
        let snapshot = try XCTUnwrap(ClipboardPasteboardReader.webURLSnapshot(for: [webURL], title: "Demo Video"))
        guard case let .link(urlString, title, _) = snapshot else {
            return XCTFail("Expected link data for web URL pasteboard objects.")
        }

        let store = makeStore(named: storeName)
        store.recordLink(
            urlString,
            title: title,
            sourceApp: ClipboardSourceApp(name: "Safari", bundleIdentifier: "com.apple.Safari"),
            preferences: .default
        )

        let item = try XCTUnwrap(store.items.first)
        XCTAssertEqual(item.kind.filter, .links)
        XCTAssertEqual(item.title, "Demo Video")
        XCTAssertTrue(item.matchesSearchQuery("youtube.com/watch"))
        XCTAssertTrue(item.matchesSearchQuery("Safari"))
    }

    func testHistoryIndexAndImageAssetsAreEncryptedAndReloadable() throws {
        let storeName = "ClipboardHistoryStoreTests.encryption"
        removeStore(named: storeName)
        defer { removeStore(named: storeName) }

        let store = makeStore(named: storeName)
        store.recordText("highly sensitive test value", sourceApp: nil, preferences: .default)
        let imageData = Data(repeating: 42, count: 128)
        store.recordImageData(imageData, sourceApp: nil, preferences: .default)

        let root = FileManager.default.temporaryDirectory.appendingPathComponent(storeName, isDirectory: true)
        let indexData = try Data(contentsOf: root.appendingPathComponent("clipboard-history.json"))
        XCTAssertTrue(indexData.starts(with: ClipboardHistoryCryptor.envelopeMagic))
        XCTAssertNil(String(data: indexData, encoding: .utf8)?.range(of: "highly sensitive test value"))

        let assets = try FileManager.default.contentsOfDirectory(
            at: root.appendingPathComponent("assets", isDirectory: true),
            includingPropertiesForKeys: nil
        )
        XCTAssertFalse(assets.isEmpty)
        XCTAssertTrue(try Data(contentsOf: XCTUnwrap(assets.first)).starts(with: ClipboardHistoryCryptor.envelopeMagic))

        let reloaded = makeStore(named: storeName)
        XCTAssertEqual(reloaded.items.count, 2)
        let imageItem = try XCTUnwrap(reloaded.items.first(where: { $0.kind.filter == .images }))
        XCTAssertEqual(reloaded.dataForPasteboard(for: imageItem), imageData)
    }

    func testDisabledHistoryDefersStoredHistoryAndKeyAccessUntilOptIn() throws {
        let storeName = "ClipboardHistoryStoreTests.deferredKeyAccess"
        removeStore(named: storeName)
        defer { removeStore(named: storeName) }

        let root = FileManager.default.temporaryDirectory.appendingPathComponent(storeName, isDirectory: true)
        let writer = ClipboardHistoryStore(baseURL: root, keyProvider: TestClipboardEncryptionKeyProvider())
        writer.recordText("stored before restart", sourceApp: nil, preferences: .default)

        let countingProvider = CountingClipboardEncryptionKeyProvider()
        let disabledStore = ClipboardHistoryStore(
            baseURL: root,
            keyProvider: countingProvider,
            loadStoredHistory: false
        )

        XCTAssertEqual(countingProvider.requestCount, 0)
        XCTAssertTrue(disabledStore.items.isEmpty)

        disabledStore.activateStorage()

        XCTAssertEqual(countingProvider.requestCount, 1)
        XCTAssertEqual(disabledStore.items.first?.previewText, "stored before restart")

        disabledStore.deactivateStorage()
        XCTAssertTrue(disabledStore.items.isEmpty)

        disabledStore.activateStorage()
        XCTAssertEqual(countingProvider.requestCount, 2)
        XCTAssertEqual(disabledStore.items.first?.previewText, "stored before restart")
    }

    func testCorruptIndexIsPreservedAndReported() throws {
        let storeName = "ClipboardHistoryStoreTests.corrupt"
        removeStore(named: storeName)
        defer { removeStore(named: storeName) }
        let root = FileManager.default.temporaryDirectory.appendingPathComponent(storeName, isDirectory: true)
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
        try Data("not-json".utf8).write(to: root.appendingPathComponent("clipboard-history.json"))

        let store = makeStore(named: storeName)
        XCTAssertTrue(store.items.isEmpty)
        XCTAssertNotNil(store.recoveryMessage)
        let files = try FileManager.default.contentsOfDirectory(atPath: root.path)
        XCTAssertTrue(files.contains(where: { $0.hasPrefix("clipboard-history-corrupt-") }))
    }

    func testRichRepresentationsAndMultiplePasteboardItemsRoundTrip() throws {
        let storeName = "ClipboardHistoryStoreTests.representations"
        removeStore(named: storeName)
        defer { removeStore(named: storeName) }
        let store = makeStore(named: storeName)
        let snapshots = [
            PasteboardItemSnapshot(representations: [
                PasteboardRepresentationSnapshot(typeIdentifier: NSPasteboard.PasteboardType.string.rawValue, data: Data("Styled".utf8)),
                PasteboardRepresentationSnapshot(typeIdentifier: NSPasteboard.PasteboardType.rtf.rawValue, data: Data("{\\rtf1 Styled}".utf8))
            ]),
            PasteboardItemSnapshot(representations: [
                PasteboardRepresentationSnapshot(typeIdentifier: NSPasteboard.PasteboardType.string.rawValue, data: Data("Second".utf8))
            ])
        ]

        store.recordText("Styled", sourceApp: nil, preferences: .default, pasteboardItems: snapshots)
        let item = try XCTUnwrap(store.items.first)
        XCTAssertEqual(store.pasteboardItemSnapshots(for: item), snapshots)
    }

    func testRetentionExpiresOnlyUnpinnedItems() throws {
        let storeName = "ClipboardHistoryStoreTests.retention"
        removeStore(named: storeName)
        defer { removeStore(named: storeName) }
        let store = makeStore(named: storeName)
        var preferences = ClipboardPreferences.default
        preferences.retentionDays = 7
        let oldDate = Calendar.current.date(byAdding: .day, value: -30, to: Date())!
        store.recordText("old pinned", sourceApp: nil, preferences: .default, copiedAt: oldDate)
        store.togglePinned(try XCTUnwrap(store.items.first))
        store.recordText("old unpinned", sourceApp: nil, preferences: .default, copiedAt: oldDate)
        store.recordText("current", sourceApp: nil, preferences: .default)

        store.prune(using: preferences)
        XCTAssertEqual(Set(store.items.map(\.previewText)), ["old pinned", "current"])
    }

    func testMaximumItemSizeRejectsOversizedPayloadBeforeWritingAssets() throws {
        let storeName = "ClipboardHistoryStoreTests.itemLimit"
        removeStore(named: storeName)
        defer { removeStore(named: storeName) }
        let store = makeStore(named: storeName)
        var preferences = ClipboardPreferences.default
        preferences.maxItemSizeMB = 1
        store.recordImageData(Data(repeating: 1, count: 2 * 1_024 * 1_024), sourceApp: nil, preferences: preferences)
        XCTAssertTrue(store.items.isEmpty)
    }

    func testSemanticTextTypesAreIndexed() throws {
        let storeName = "ClipboardHistoryStoreTests.semantic"
        removeStore(named: storeName)
        defer { removeStore(named: storeName) }
        let store = makeStore(named: storeName)
        store.recordText(#"{"name":"Snip"}"#, sourceApp: nil, preferences: .default)
        let json = try XCTUnwrap(store.items.first)
        XCTAssertEqual(json.semanticType, .json)
        XCTAssertTrue(json.matchesSearchQuery("JSON"))

        store.recordText("#12ab34", sourceApp: nil, preferences: .default)
        XCTAssertEqual(store.items.first?.semanticType, .color)
    }

    func testNamedCollectionsPersistAcrossReloadAndRemainSearchable() throws {
        let storeName = "ClipboardHistoryStoreTests.collections"
        removeStore(named: storeName)
        defer { removeStore(named: storeName) }
        let store = makeStore(named: storeName)
        store.recordText("release checklist", sourceApp: nil, preferences: .default)
        store.toggleCollection("Shipping", for: try XCTUnwrap(store.items.first))

        let reloaded = makeStore(named: storeName)
        let item = try XCTUnwrap(reloaded.items.first)
        XCTAssertEqual(item.collectionNames, ["Shipping"])
        XCTAssertTrue(item.matchesSearchQuery("shipping"))
    }

    func testEmptyExplicitSourceFallsBackToFrontmostApplication() throws {
        let fallback = ClipboardSourceApp(name: "Notes", bundleIdentifier: "com.apple.Notes")
        let source = ClipboardPasteboardReader.sourceApp(
            forPasteboardTypeNames: [ClipboardPasteboardReader.sourceTypeName],
            explicitSourceIdentifier: "  ",
            fallbackSourceApp: fallback,
            workspace: TestWorkspaceService()
        )
        XCTAssertEqual(source, fallback)
    }

    func testFailedTransactionalWriteRestoresPreviousClipboard() throws {
        let pasteboard = TestPasteboardService()
        pasteboard.setString("keep me", forType: .string)
        pasteboard.failNextSnapshotWrite()
        let replacement = [PasteboardItemSnapshot(representations: [
            PasteboardRepresentationSnapshot(typeIdentifier: NSPasteboard.PasteboardType.string.rawValue, data: Data("replacement".utf8))
        ])]

        XCTAssertFalse(ClipboardPasteboardTransaction.commit(
            pasteboard: pasteboard,
            preparedItems: replacement,
            fallbackWrite: { false }
        ))
        XCTAssertEqual(pasteboard.string(forType: .string), "keep me")
    }

    private static func jpegData() -> Data? {
        guard let representation = NSBitmapImageRep(
            bitmapDataPlanes: nil,
            pixelsWide: 2,
            pixelsHigh: 2,
            bitsPerSample: 8,
            samplesPerPixel: 4,
            hasAlpha: true,
            isPlanar: false,
            colorSpaceName: .deviceRGB,
            bytesPerRow: 0,
            bitsPerPixel: 0
        ) else {
            return nil
        }

        NSGraphicsContext.saveGraphicsState()
        NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: representation)
        NSColor.systemBlue.setFill()
        NSRect(x: 0, y: 0, width: 2, height: 2).fill()
        NSGraphicsContext.restoreGraphicsState()

        return representation.representation(using: .jpeg, properties: [:])
    }

}

private actor ControlledClipboardSnapshotResolver {
    private var texts: [String] = []
    private var continuations: [CheckedContinuation<Void, Never>] = []

    var captureCount: Int {
        texts.count
    }

    var capturedTexts: [String] {
        texts
    }

    func resolve(
        _ content: ClipboardCapturedPasteboardContent
    ) async -> ClipboardPasteboardSnapshot? {
        let text = content.text ?? ""
        texts.append(text)
        await withCheckedContinuation { continuation in
            continuations.append(continuation)
        }
        return .text(text)
    }

    func releaseNext() {
        guard !continuations.isEmpty else {
            return
        }
        continuations.removeFirst().resume()
    }
}

@MainActor
private final class TestPasteboardService: PasteboardServicing, @unchecked Sendable {
    private var strings: [NSPasteboard.PasteboardType: String] = [:]
    private var dataByType: [NSPasteboard.PasteboardType: Data] = [:]
    private var urls: [URL] = []
    private var snapshotWriteFailuresRemaining = 0

    private(set) var changeCount = 0

    var typeNames: [String] {
        Array(Set(strings.keys.map(\.rawValue) + dataByType.keys.map(\.rawValue)))
    }

    @discardableResult
    func clearContents() -> Bool {
        strings.removeAll()
        dataByType.removeAll()
        urls.removeAll()
        changeCount += 1
        return true
    }

    func fileAndWebURLs() -> [URL] {
        urls
    }

    func data(forType type: NSPasteboard.PasteboardType) -> Data? {
        dataByType[type]
    }

    func string(forType type: NSPasteboard.PasteboardType) -> String? {
        strings[type]
    }

    func itemSnapshots(acceptedTypeIdentifiers: Set<String>) -> [PasteboardItemSnapshot] {
        let representations = dataByType.compactMap { type, data in
            acceptedTypeIdentifiers.contains(type.rawValue)
                ? PasteboardRepresentationSnapshot(typeIdentifier: type.rawValue, data: data)
                : nil
        }
        return representations.isEmpty ? [] : [PasteboardItemSnapshot(representations: representations)]
    }

    @discardableResult
    func setString(_ string: String, forType type: NSPasteboard.PasteboardType) -> Bool {
        strings[type] = string
        dataByType[type] = Data(string.utf8)
        changeCount += 1
        return true
    }

    @discardableResult
    func setData(_ data: Data, forType type: NSPasteboard.PasteboardType) -> Bool {
        dataByType[type] = data
        changeCount += 1
        return true
    }

    @discardableResult
    func writeFileURLs(_ urls: [URL]) -> Bool {
        self.urls = urls
        changeCount += 1
        return true
    }

    @discardableResult
    func writeItemSnapshots(_ items: [PasteboardItemSnapshot]) -> Bool {
        if snapshotWriteFailuresRemaining > 0 {
            snapshotWriteFailuresRemaining -= 1
            return false
        }
        guard !items.isEmpty else { return false }
        strings.removeAll()
        dataByType.removeAll()
        for item in items {
            for representation in item.representations {
                dataByType[NSPasteboard.PasteboardType(representation.typeIdentifier)] = representation.data
                if representation.typeIdentifier == NSPasteboard.PasteboardType.string.rawValue {
                    strings[.string] = String(data: representation.data, encoding: .utf8)
                }
            }
        }
        changeCount += 1
        return true
    }

    func failNextSnapshotWrite() {
        snapshotWriteFailuresRemaining += 1
    }

    func addType(_ typeName: String) {
        dataByType[NSPasteboard.PasteboardType(typeName)] = Data()
        changeCount += 1
    }
}

nonisolated private struct TestClipboardEncryptionKeyProvider: ClipboardEncryptionKeyProviding {
    func encryptionKey() throws -> SymmetricKey {
        SymmetricKey(data: Data(repeating: 0x5a, count: 32))
    }
}

nonisolated private final class CountingClipboardEncryptionKeyProvider: ClipboardEncryptionKeyProviding, @unchecked Sendable {
    private let lock = NSLock()
    private var storedRequestCount = 0

    var requestCount: Int {
        lock.withLock { storedRequestCount }
    }

    func encryptionKey() throws -> SymmetricKey {
        lock.withLock {
            storedRequestCount += 1
        }
        return SymmetricKey(data: Data(repeating: 0x5a, count: 32))
    }
}
