import AppKit
import Combine
import Foundation
import UniformTypeIdentifiers

enum ClipboardPasteboardReader {
    static let remoteClipboardTypeName = "com.apple.is-remote-clipboard"
    static let sourceTypeName = "org.nspasteboard.source"

    static let concealedAndTransientTypeNames: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType"
    ]

    static func containsSensitiveOrTransientType(_ typeNames: [String]) -> Bool {
        !Set(typeNames).isDisjoint(with: concealedAndTransientTypeNames)
    }

    static func sourceApp(
        forPasteboardTypeNames typeNames: [String],
        explicitSourceIdentifier: String?,
        fallbackSourceApp: ClipboardSourceApp?
    ) -> ClipboardSourceApp? {
        if let explicitSourceIdentifier {
            let sourceIdentifier = explicitSourceIdentifier.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !sourceIdentifier.isEmpty else {
                return nil
            }

            return sourceApp(forSourceIdentifier: sourceIdentifier)
        }

        if typeNames.contains(remoteClipboardTypeName) {
            return ClipboardSourceApp(
                name: "Universal Clipboard",
                bundleIdentifier: remoteClipboardTypeName
            )
        }

        return fallbackSourceApp
    }

    @MainActor
    static func readGeneralPasteboard(
        sourceApp: ClipboardSourceApp?,
        preferences: ClipboardPreferences
    ) -> ClipboardPasteboardSnapshot? {
        let pasteboard = NSPasteboard.general
        let typeNames = pasteboard.types?.map(\.rawValue) ?? []

        guard !containsSensitiveOrTransientType(typeNames),
              !preferences.ignores(sourceApp) else {
            return nil
        }

        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL],
           !urls.isEmpty {
            let fileURLs = urls.filter(\.isFileURL)
            let webURLs = urls.filter(isWebURL)

            if fileURLs.count == urls.count,
               let imageSnapshot = imageFileSnapshot(for: fileURLs) {
                return imageSnapshot
            }

            if fileURLs.count == urls.count {
                return .fileURLs(fileURLs)
            }

            if let webURL = webURLs.first {
                return .link(
                    webURL.absoluteString,
                    title: urlTitle(from: pasteboard),
                    searchableText: nil
                )
            }
        }

        if let pngData = pasteboard.data(forType: .png), !pngData.isEmpty {
            return .imageData(pngData)
        }

        if let tiffData = pasteboard.data(forType: .tiff),
           let image = NSImage(data: tiffData),
           let cgImage = image.cgImage(forProposedRect: nil, context: nil, hints: nil),
           let pngData = try? ImageExporter.pngData(for: cgImage) {
            return .imageData(pngData)
        }

        if let text = pasteboard.string(forType: .string), !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return .text(text)
        }

        return nil
    }

    static func webURLSnapshot(for urls: [URL], title: String? = nil) -> ClipboardPasteboardSnapshot? {
        guard let webURL = urls.first(where: isWebURL) else {
            return nil
        }

        return .link(webURL.absoluteString, title: title, searchableText: nil)
    }

    static func imageFileSnapshot(for urls: [URL]) -> ClipboardPasteboardSnapshot? {
        let imageURLs = urls.filter(isImageFileURL)
        guard !imageURLs.isEmpty,
              imageURLs.count == urls.count,
              let firstImageURL = imageURLs.first,
              let image = NSImage(contentsOf: firstImageURL),
              let cgImage = image.cgImage(forProposedRect: nil, context: nil, hints: nil),
              let pngData = try? ImageExporter.pngData(for: cgImage) else {
            return nil
        }

        let title: String
        if imageURLs.count == 1 {
            title = firstImageURL.lastPathComponent
        } else {
            title = "\(imageURLs.count) images"
        }

        let searchableText = imageURLs
            .map { [$0.lastPathComponent, $0.path].joined(separator: " ") }
            .joined(separator: " ")

        return .imageData(pngData, title: title, searchableText: searchableText)
    }

    private static func isImageFileURL(_ url: URL) -> Bool {
        guard url.isFileURL else {
            return false
        }

        let extensionText = url.pathExtension.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !extensionText.isEmpty else {
            return false
        }

        if let type = UTType(filenameExtension: extensionText),
           type.conforms(to: .image) {
            return true
        }

        return ["jpg", "jpeg", "png", "heic", "heif", "tif", "tiff", "gif", "bmp", "webp"]
            .contains(extensionText.localizedLowercase)
    }

    private static func isWebURL(_ url: URL) -> Bool {
        ["http", "https", "mailto"].contains(url.scheme?.localizedLowercase ?? "")
    }

    private static func urlTitle(from pasteboard: NSPasteboard) -> String? {
        [
            "public.url-name",
            "Apple URL name pasteboard type"
        ]
        .lazy
        .compactMap { pasteboard.string(forType: NSPasteboard.PasteboardType($0)) }
        .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
        .first { !$0.isEmpty }
    }

    private static func sourceApp(forSourceIdentifier sourceIdentifier: String) -> ClipboardSourceApp {
        let appURL = NSWorkspace.shared.urlForApplication(withBundleIdentifier: sourceIdentifier)
        let bundle = appURL.flatMap(Bundle.init(url:))
        let displayName = bundle?.object(forInfoDictionaryKey: "CFBundleDisplayName") as? String
            ?? bundle?.object(forInfoDictionaryKey: "CFBundleName") as? String
            ?? appURL?.deletingPathExtension().lastPathComponent

        return ClipboardSourceApp(
            name: displayName ?? sourceIdentifier,
            bundleIdentifier: sourceIdentifier
        )
    }
}

enum ClipboardPasteboardSnapshot: Equatable {
    case text(String)
    case link(String, title: String? = nil, searchableText: String? = nil)
    case imageData(Data, title: String = "Image", searchableText: String? = nil)
    case fileURLs([URL])
}

@MainActor
final class ClipboardMonitor {
    private let store: ClipboardHistoryStore
    private var timer: Timer?
    private var observedChangeCount: Int

    init(store: ClipboardHistoryStore) {
        self.store = store
        observedChangeCount = NSPasteboard.general.changeCount
    }

    func start(preferences: ClipboardPreferences) {
        stop()
        observedChangeCount = NSPasteboard.general.changeCount

        guard preferences.isEnabled else {
            return
        }

        timer = Timer.scheduledTimer(withTimeInterval: 0.7, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in
                self?.poll(preferences: preferences)
            }
        }
    }

    func update(preferences: ClipboardPreferences) {
        if preferences.isEnabled {
            if timer == nil {
                start(preferences: preferences)
            } else {
                poll(preferences: preferences)
            }
        } else {
            stop()
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func markCurrentPasteboardChangeAsHandled() {
        observedChangeCount = NSPasteboard.general.changeCount
    }

    private func poll(preferences: ClipboardPreferences) {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != observedChangeCount else {
            return
        }

        observedChangeCount = pasteboard.changeCount
        let typeNames = pasteboard.types?.map(\.rawValue) ?? []
        let hasExplicitSource = typeNames.contains(ClipboardPasteboardReader.sourceTypeName)
        let explicitSourceIdentifier = hasExplicitSource
            ? (pasteboard.string(forType: NSPasteboard.PasteboardType(ClipboardPasteboardReader.sourceTypeName)) ?? "")
            : nil
        let sourceApp = ClipboardPasteboardReader.sourceApp(
            forPasteboardTypeNames: typeNames,
            explicitSourceIdentifier: explicitSourceIdentifier,
            fallbackSourceApp: Self.currentSourceApp()
        )
        let sanitizedPreferences = preferences.sanitized()

        guard let snapshot = ClipboardPasteboardReader.readGeneralPasteboard(
            sourceApp: sourceApp,
            preferences: sanitizedPreferences
        ) else {
            return
        }

        switch snapshot {
        case let .text(text):
            store.recordText(text, sourceApp: sourceApp, preferences: sanitizedPreferences)
        case let .link(urlString, title, searchableText):
            store.recordLink(
                urlString,
                title: title,
                searchableText: searchableText,
                sourceApp: sourceApp,
                preferences: sanitizedPreferences
            )
        case let .imageData(data, title, searchableText):
            store.recordImageData(
                data,
                sourceApp: sourceApp,
                preferences: sanitizedPreferences,
                title: title,
                searchableText: searchableText
            )
        case let .fileURLs(urls):
            store.recordFileURLs(urls, sourceApp: sourceApp, preferences: sanitizedPreferences)
        }
    }

    private static func currentSourceApp() -> ClipboardSourceApp? {
        guard let app = NSWorkspace.shared.frontmostApplication else {
            return nil
        }

        return ClipboardSourceApp(
            name: app.localizedName,
            bundleIdentifier: app.bundleIdentifier
        )
    }
}
