import AppKit
import Combine
import Foundation
import UniformTypeIdentifiers

enum ClipboardPasteboardReader {
    static let remoteClipboardTypeName = "com.apple.is-remote-clipboard"
    static let sourceTypeName = "org.nspasteboard.source"
    static let autoGeneratedTypeName = "org.nspasteboard.AutoGeneratedType"
    static let preservedTypeIdentifiers: Set<String> = [
        NSPasteboard.PasteboardType.string.rawValue,
        NSPasteboard.PasteboardType.rtf.rawValue,
        NSPasteboard.PasteboardType.rtfd.rawValue,
        NSPasteboard.PasteboardType.html.rawValue,
        NSPasteboard.PasteboardType.png.rawValue,
        NSPasteboard.PasteboardType.tiff.rawValue,
        NSPasteboard.PasteboardType.pdf.rawValue,
        NSPasteboard.PasteboardType.fileURL.rawValue,
        NSPasteboard.PasteboardType.URL.rawValue,
        NSPasteboard.PasteboardType.color.rawValue,
        "public.jpeg",
        "public.heic",
        "public.heif-standard",
        "com.compuserve.gif",
        "public.svg-image"
    ]
    static let previewableBinaryTypeIdentifiers = [
        NSPasteboard.PasteboardType.pdf.rawValue,
        "public.jpeg",
        "public.heic",
        "public.heif-standard",
        "com.compuserve.gif",
        "public.svg-image"
    ]

    static let concealedAndTransientTypeNames: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType"
    ]

    static func containsSensitiveOrTransientType(_ typeNames: [String]) -> Bool {
        !Set(typeNames).isDisjoint(with: concealedAndTransientTypeNames)
    }

    static func sourceApp(
        forPasteboardTypeNames typeNames: [String],
        explicitSourceIdentifier: String?,
        fallbackSourceApp: ClipboardSourceApp?,
        workspace: any WorkspaceServicing
    ) -> ClipboardSourceApp? {
        if let explicitSourceIdentifier {
            let sourceIdentifier = explicitSourceIdentifier.trimmingCharacters(in: .whitespacesAndNewlines)
            if !sourceIdentifier.isEmpty {
                return sourceApp(forSourceIdentifier: sourceIdentifier, workspace: workspace)
            }
        }

        if typeNames.contains(remoteClipboardTypeName) {
            return ClipboardSourceApp(
                name: "Universal Clipboard",
                bundleIdentifier: remoteClipboardTypeName
            )
        }

        return fallbackSourceApp
    }

    @MainActor
    static func readPasteboard(
        _ pasteboard: any PasteboardServicing,
        sourceApp: ClipboardSourceApp?,
        preferences: ClipboardPreferences
    ) -> ClipboardPasteboardSnapshot? {
        let typeNames = pasteboard.typeNames

        guard !containsSensitiveOrTransientType(typeNames),
              !preferences.ignores(sourceApp) else {
            return nil
        }

        let urls = pasteboard.fileAndWebURLs()
        if !urls.isEmpty {
            let fileURLs = urls.filter(\.isFileURL)
            let webURLs = urls.filter(isWebURL)

            if fileURLs.count == urls.count,
               let imageSnapshot = imageFileSnapshot(for: fileURLs) {
                return imageSnapshot
            }

            if fileURLs.count == urls.count {
                return .fileURLs(fileURLs)
            }

            if let webURL = webURLs.first {
                return .link(
                    webURL.absoluteString,
                    title: urlTitle(from: pasteboard),
                    searchableText: nil
                )
            }
        }

        if let pngData = pasteboard.data(forType: .png), !pngData.isEmpty {
            return .imageData(pngData)
        }

        if let tiffData = pasteboard.data(forType: .tiff),
           let image = NSImage(data: tiffData),
           let cgImage = image.cgImage(forProposedRect: nil, context: nil, hints: nil),
           let pngData = try? ImageExporter.pngData(for: cgImage) {
            return .imageData(pngData)
        }

        if let text = pasteboard.string(forType: .string), !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return .text(text)
        }

        return nil
    }

    @MainActor
    static func readPasteboardAsync(
        _ pasteboard: any PasteboardServicing,
        sourceApp: ClipboardSourceApp?,
        preferences: ClipboardPreferences
    ) async -> ClipboardPasteboardSnapshot? {
        guard let captured = capturePasteboardContent(
            pasteboard,
            sourceApp: sourceApp,
            preferences: preferences
        ) else {
            return nil
        }
        return await resolveSnapshot(from: captured)
    }

    @MainActor
    static func capturePasteboardContent(
        _ pasteboard: any PasteboardServicing,
        sourceApp: ClipboardSourceApp?,
        preferences: ClipboardPreferences
    ) -> ClipboardCapturedPasteboardContent? {
        let typeNames = pasteboard.typeNames
        guard !containsSensitiveOrTransientType(typeNames),
              !preferences.ignores(sourceApp) else {
            return nil
        }

        return ClipboardCapturedPasteboardContent(
            urls: pasteboard.fileAndWebURLs(),
            pngData: pasteboard.data(forType: .png),
            tiffData: pasteboard.data(forType: .tiff),
            text: pasteboard.string(forType: .string),
            urlTitle: urlTitle(from: pasteboard),
            previewableBinaryRepresentations: previewableBinaryTypeIdentifiers.compactMap { typeIdentifier in
                guard let data = pasteboard.data(forType: NSPasteboard.PasteboardType(typeIdentifier)),
                      !data.isEmpty else { return nil }
                return ClipboardCapturedBinaryRepresentation(typeIdentifier: typeIdentifier, data: data)
            }
        )
    }

    static func resolveSnapshot(
        from captured: ClipboardCapturedPasteboardContent
    ) async -> ClipboardPasteboardSnapshot? {
        // Clipboard images are processed as part of the copy event. Run OCR
        // at user-initiated QoS so Vision does not make the calling task wait
        // on utility-priority work.
        let task = Task.detached(priority: .userInitiated) {
            snapshot(from: captured)
        }
        return await withTaskCancellationHandler {
            await task.value
        } onCancel: {
            task.cancel()
        }
    }

    nonisolated private static func snapshot(
        from captured: ClipboardCapturedPasteboardContent
    ) -> ClipboardPasteboardSnapshot? {
        guard !Task.isCancelled else {
            return nil
        }
        if !captured.urls.isEmpty {
            let fileURLs = captured.urls.filter(\.isFileURL)
            let webURLs = captured.urls.filter(isWebURL)
            if fileURLs.count == captured.urls.count,
               let imageSnapshot = imageFileSnapshot(for: fileURLs) {
                return imageSnapshot
            }
            if fileURLs.count == captured.urls.count {
                return .fileURLs(fileURLs)
            }
            if let webURL = webURLs.first {
                return .link(webURL.absoluteString, title: captured.urlTitle, searchableText: nil)
            }
        }
        if let pngData = captured.pngData, !pngData.isEmpty {
            guard !Task.isCancelled else { return nil }
            return .imageData(
                pngData,
                title: "Image",
                searchableText: ClipboardTextRecognition.recognizedText(in: pngData)
            )
        }
        if let tiffData = captured.tiffData,
           !Task.isCancelled,
           let image = NSImage(data: tiffData),
           let cgImage = image.cgImage(forProposedRect: nil, context: nil, hints: nil),
           let pngData = try? ImageExporter.pngData(for: cgImage) {
            return .imageData(
                pngData,
                title: "Image",
                searchableText: ClipboardTextRecognition.recognizedText(in: pngData)
            )
        }
        for representation in captured.previewableBinaryRepresentations {
            guard !Task.isCancelled else { return nil }
            guard let image = NSImage(data: representation.data),
                  let cgImage = image.cgImage(forProposedRect: nil, context: nil, hints: nil),
                  let pngData = try? ImageExporter.pngData(for: cgImage) else {
                continue
            }
            let title = representation.typeIdentifier == NSPasteboard.PasteboardType.pdf.rawValue ? "PDF" : "Image"
            return .imageData(
                pngData,
                title: title,
                searchableText: ClipboardTextRecognition.recognizedText(in: pngData)
            )
        }
        if let text = captured.text, !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return .text(text)
        }
        return nil
    }

    static func webURLSnapshot(for urls: [URL], title: String? = nil) -> ClipboardPasteboardSnapshot? {
        guard let webURL = urls.first(where: isWebURL) else {
            return nil
        }

        return .link(webURL.absoluteString, title: title, searchableText: nil)
    }

    nonisolated static func imageFileSnapshot(for urls: [URL]) -> ClipboardPasteboardSnapshot? {
        let imageURLs = urls.filter(isImageFileURL)
        guard !imageURLs.isEmpty,
              imageURLs.count == urls.count,
              let firstImageURL = imageURLs.first,
              let image = NSImage(contentsOf: firstImageURL),
              let cgImage = image.cgImage(forProposedRect: nil, context: nil, hints: nil),
              let pngData = try? ImageExporter.pngData(for: cgImage) else {
            return nil
        }

        let title: String
        if imageURLs.count == 1 {
            title = firstImageURL.lastPathComponent
        } else {
            title = "\(imageURLs.count) images"
        }

        let pathSearchableText = imageURLs
            .map { [$0.lastPathComponent, $0.path].joined(separator: " ") }
            .joined(separator: " ")
        let recognizedText = ClipboardTextRecognition.recognizedText(in: pngData)
        let searchableText = [pathSearchableText, recognizedText]
            .filter { !$0.isEmpty }
            .joined(separator: " ")

        return .imageData(pngData, title: title, searchableText: searchableText)
    }

    nonisolated private static func isImageFileURL(_ url: URL) -> Bool {
        guard url.isFileURL else {
            return false
        }

        let extensionText = url.pathExtension.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !extensionText.isEmpty else {
            return false
        }

        if let type = UTType(filenameExtension: extensionText),
           type.conforms(to: .image) {
            return true
        }

        return ["jpg", "jpeg", "png", "heic", "heif", "tif", "tiff", "gif", "bmp", "webp"]
            .contains(extensionText.localizedLowercase)
    }

    nonisolated private static func isWebURL(_ url: URL) -> Bool {
        ["http", "https", "mailto"].contains(url.scheme?.localizedLowercase ?? "")
    }

    @MainActor
    private static func urlTitle(from pasteboard: any PasteboardServicing) -> String? {
        [
            "public.url-name",
            "Apple URL name pasteboard type"
        ]
        .lazy
        .compactMap { pasteboard.string(forType: NSPasteboard.PasteboardType($0)) }
        .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
        .first { !$0.isEmpty }
    }

    private static func sourceApp(
        forSourceIdentifier sourceIdentifier: String,
        workspace: any WorkspaceServicing
    ) -> ClipboardSourceApp {
        let appURL = workspace.applicationURL(forBundleIdentifier: sourceIdentifier)
        let bundle = appURL.flatMap(Bundle.init(url:))
        let displayName = bundle?.object(forInfoDictionaryKey: "CFBundleDisplayName") as? String
            ?? bundle?.object(forInfoDictionaryKey: "CFBundleName") as? String
            ?? appURL?.deletingPathExtension().lastPathComponent

        return ClipboardSourceApp(
            name: displayName ?? sourceIdentifier,
            bundleIdentifier: sourceIdentifier
        )
    }
}

nonisolated struct ClipboardCapturedPasteboardContent: Sendable {
    let urls: [URL]
    let pngData: Data?
    let tiffData: Data?
    let text: String?
    let urlTitle: String?
    let previewableBinaryRepresentations: [ClipboardCapturedBinaryRepresentation]
}

nonisolated struct ClipboardCapturedBinaryRepresentation: Sendable {
    let typeIdentifier: String
    let data: Data
}

enum ClipboardPasteboardSnapshot: Equatable {
    case text(String)
    case link(String, title: String? = nil, searchableText: String? = nil)
    case imageData(Data, title: String = "Image", searchableText: String? = nil)
    case fileURLs([URL])
}

typealias ClipboardSnapshotResolver = @Sendable (
    ClipboardCapturedPasteboardContent
) async -> ClipboardPasteboardSnapshot?

@MainActor
final class ClipboardMonitor {
    private struct PendingChange {
        let content: ClipboardCapturedPasteboardContent
        let sourceApp: ClipboardSourceApp?
        let preferences: ClipboardPreferences
        let pasteboardItems: [PasteboardItemSnapshot]
        let copiedAt: Date
    }

    private let store: ClipboardHistoryStore
    private let pasteboard: any PasteboardServicing
    private let workspace: any WorkspaceServicing
    private let snapshotResolver: ClipboardSnapshotResolver
    private var timer: Timer?
    private var observedChangeCount: Int
    private var currentPreferences: ClipboardPreferences?
    private var pausedUntil: Date?
    private var pendingChange: PendingChange?
    private var ingestionTask: Task<Void, Never>?
    private var activeIngestionID: UUID?

    init(
        store: ClipboardHistoryStore,
        pasteboard: any PasteboardServicing = SystemPasteboardService(),
        workspace: any WorkspaceServicing = SystemWorkspaceService(),
        snapshotResolver: @escaping ClipboardSnapshotResolver = {
            await ClipboardPasteboardReader.resolveSnapshot(from: $0)
        }
    ) {
        self.store = store
        self.pasteboard = pasteboard
        self.workspace = workspace
        self.snapshotResolver = snapshotResolver
        observedChangeCount = pasteboard.changeCount
    }

    func start(preferences: ClipboardPreferences) {
        stop()
        currentPreferences = preferences.sanitized()

        guard preferences.isEnabled else {
            return
        }

        poll(preferences: currentPreferences ?? preferences)

        let timer = Timer(timeInterval: 0.2, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in
                self?.pollCurrentPasteboard()
            }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func update(preferences: ClipboardPreferences) {
        currentPreferences = preferences.sanitized()

        if preferences.isEnabled {
            if timer == nil {
                start(preferences: preferences)
            } else {
                pollCurrentPasteboard()
            }
        } else {
            stop()
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        cancelPendingIngestion()
    }

    func markCurrentPasteboardChangeAsHandled() {
        observedChangeCount = pasteboard.changeCount
    }

    func pause(until date: Date?) {
        pausedUntil = date
        cancelPendingIngestion()
        markCurrentPasteboardChangeAsHandled()
    }

    private func pollCurrentPasteboard() {
        guard let currentPreferences else {
            return
        }

        poll(preferences: currentPreferences)
    }

    private func poll(preferences: ClipboardPreferences) {
        if let pausedUntil {
            if pausedUntil > Date() {
                observedChangeCount = pasteboard.changeCount
                return
            }
            self.pausedUntil = nil
        }

        guard pasteboard.changeCount != observedChangeCount else {
            return
        }

        observedChangeCount = pasteboard.changeCount
        let typeNames = pasteboard.typeNames
        let hasExplicitSource = typeNames.contains(ClipboardPasteboardReader.sourceTypeName)
        let explicitSourceIdentifier = hasExplicitSource
            ? (pasteboard.string(forType: NSPasteboard.PasteboardType(ClipboardPasteboardReader.sourceTypeName)) ?? "")
            : nil
        let sourceApp = ClipboardPasteboardReader.sourceApp(
            forPasteboardTypeNames: typeNames,
            explicitSourceIdentifier: explicitSourceIdentifier,
            fallbackSourceApp: Self.currentSourceApp(workspace: workspace),
            workspace: workspace
        )
        let sanitizedPreferences = preferences.sanitized()
        let pasteboardItems = pasteboard.itemSnapshots(
            acceptedTypeIdentifiers: ClipboardPasteboardReader.preservedTypeIdentifiers
        )
        guard let content = ClipboardPasteboardReader.capturePasteboardContent(
            pasteboard,
            sourceApp: sourceApp,
            preferences: sanitizedPreferences
        ) else {
            return
        }

        enqueue(PendingChange(
            content: content,
            sourceApp: sourceApp,
            preferences: sanitizedPreferences,
            pasteboardItems: pasteboardItems,
            copiedAt: Date()
        ))
    }

    private func enqueue(_ change: PendingChange) {
        pendingChange = change
        startNextIngestionIfNeeded()
    }

    private func startNextIngestionIfNeeded() {
        guard ingestionTask == nil, let change = pendingChange else {
            return
        }

        pendingChange = nil
        let ingestionID = UUID()
        let resolver = snapshotResolver
        activeIngestionID = ingestionID
        ingestionTask = Task { @MainActor [weak self] in
            let snapshot = await resolver(change.content)
            guard let self else {
                return
            }

            self.completeIngestion(
                id: ingestionID,
                change: change,
                snapshot: Task.isCancelled ? nil : snapshot
            )
        }
    }

    private func completeIngestion(
        id: UUID,
        change: PendingChange,
        snapshot: ClipboardPasteboardSnapshot?
    ) {
        guard activeIngestionID == id else {
            return
        }

        ingestionTask = nil
        activeIngestionID = nil
        if let snapshot {
            record(
                snapshot,
                sourceApp: change.sourceApp,
                preferences: change.preferences,
                pasteboardItems: change.pasteboardItems,
                copiedAt: change.copiedAt
            )
        }
        startNextIngestionIfNeeded()
    }

    private func cancelPendingIngestion() {
        ingestionTask?.cancel()
        ingestionTask = nil
        activeIngestionID = nil
        pendingChange = nil
    }

    private func record(
        _ snapshot: ClipboardPasteboardSnapshot,
        sourceApp: ClipboardSourceApp?,
        preferences: ClipboardPreferences,
        pasteboardItems: [PasteboardItemSnapshot],
        copiedAt: Date
    ) {
        switch snapshot {
        case let .text(text):
            store.recordText(
                text,
                sourceApp: sourceApp,
                preferences: preferences,
                copiedAt: copiedAt,
                pasteboardItems: pasteboardItems
            )
        case let .link(urlString, title, searchableText):
            store.recordLink(
                urlString,
                title: title,
                searchableText: searchableText,
                sourceApp: sourceApp,
                preferences: preferences,
                copiedAt: copiedAt,
                pasteboardItems: pasteboardItems
            )
        case let .imageData(data, title, searchableText):
            store.recordImageData(
                data,
                sourceApp: sourceApp,
                preferences: preferences,
                copiedAt: copiedAt,
                title: title,
                searchableText: searchableText,
                pasteboardItems: pasteboardItems
            )
        case let .fileURLs(urls):
            store.recordFileURLs(
                urls,
                sourceApp: sourceApp,
                preferences: preferences,
                copiedAt: copiedAt,
                pasteboardItems: pasteboardItems
            )
        }
    }

    private static func currentSourceApp(workspace: any WorkspaceServicing) -> ClipboardSourceApp? {
        guard let app = workspace.frontmostApplication else {
            return nil
        }

        return ClipboardSourceApp(
            name: app.localizedName,
            bundleIdentifier: app.bundleIdentifier
        )
    }
}
